(define (loops n)
  (let ((acc 0))
    (do ((i1 n (- i1 1))) ((= i1 0))
      (do ((i2 n (- i2 1))) ((= i2 0))
        (do ((i3 n (- i3 1))) ((= i3 0))
          (do ((i4 n (- i4 1))) ((= i4 0))
            (set! acc (+ acc 1))))))
    acc))

(loops 18)
