;;; Another nested inter-procedure loop. Was showing stack element type
;;; error.

(define (nest n)
  (let lp ((i1 n) (acc 0))
    (if (< 0 i1)
        (lp (- i1 1)
            (let lp ((i2 n) (acc acc))
              (if (< 0 i2)
                  (lp (- i2 1)
                      (let lp ((i3 n) (acc acc))
                        (if (< 0 i3)
                            (lp (- i3 1)
                                (let lp ((i4 n) (acc acc))
                                  (if (< 0 i4)
                                      (lp (- i4 1)
                                          (let lp ((i5 n) (acc acc))
                                            (if (< 0 i5)
                                                (lp (- i5 1)
                                                    (let lp ((i6 n) (acc acc))
                                                      (if (< 0 i6)
                                                          (lp (- i6 1) (+ acc 1))
                                                          acc)))
                                                acc)))
                                      acc)))
                            acc)))
                  acc)))
        acc)))

(define (run-nest n)
  (let lp ((n n) (v 0))
    (if (< 0 n)
        (lp (- n 1) (+ v (nest 15)))
        v)))

(run-nest 15)
