(let ((i1 1)
      (j1 1)
      (k1 0))
  (letrec ((f2 (lambda (j2 k2)
                 (if (< k2 #e1e5)
                     (if (< j2 20)
                         (let ((j3 i1)
                               (k3 (+ k2 1)))
                           (f7 j3 k3))
                         (let ((j5 k2)
                               (k5 (+ k2 1)))
                           (f7 j5 k5)))
                     j2)))
           (f7 (lambda (j4 k4)
                 (f2 j4 k4))))
    (f2 j1 k1)))
